### ISSUE TITLE
Home page link yields 404

### ISSUE THREAD

**Issue by band** [Massive-Wiki/massive-wiki#3]
from this page;  https://massive.wiki/

 the Massive Wiki Starter Guidebook, i.e. this page:  
     https://massive.wiki/Massive_Wiki_Starter_Guidebook_Table_Of_Contents.html

isn't there. 

(sent to me from @applemcg)

**Comment by peterkaminski** [comment]
Thanks, Bill!

I'd bumped into this, but it was during a demo, so I didn't capture it.

I'll fix it.

**Comment by peterkaminski** [comment]
## Fix

Just added an absolute path.  (And used `closes #3` in the Obsidian commit message, so workflow-wise, I closed this issue directly from Obsidian!)

## Related Fix

I included a 404.md file, which wouldn't have fixed the problem, but does make a better 404 message.

## Background

In Obsidian, you can use "short" links without a directory path, and Obsidian just figures out the right file (unless there are multiple files, and then it just picks an arbitrary one).  Massive Wiki Builder isn't that smart, it needs an absolute path.  (Which then makes the link ugly...)

(the ugliness is when you have to have the link and then the link text (separated with the vertical bar)).

at some point, MWB will handle short links, so we can go back to short links.
